[package]
name = "billliu"
version = "0.1.0"
authors = ["Bill Liu <liu_bill@live.com>"]
edition = "2018"

[dependencies]
grass = "0.10.3"
handlebars = "3.5.0" 
comrak = "0.8.2"
toml = "0.5"
notify = "4.0.15"
serde = { version = "1.0.117", features = ["derive"]}
